### PR TITLE
[3198] fix stopping prover on branches + logging unproven

### LINKED ISSUE #3198: pyk integration test failure since new graph traversal
The rewrite in #3168 causes a pyk integration test ( `test_get_basic_block (pyk.integration_tests.test_kprove.ImpProofTest)` in the K repository) to fail. It appears to output `#Top` where it should return an unproven configuration.

### PR DESCRIPTION
**Pull request by jberthold**
* The rewritten prover was returning a final instead of a stopped state when stopping at branches
* Proof depth for unproven claims was not logged at info level as before.

This fixes both problems, and adds a unit test for stopping at branches.

Fixes #3198

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/src/Kore/Exec/GraphTraversal.hs [hunk 1]
```diff
@@ -263,8 +267,8 @@ graphTraversal
             Seq (TState instr config) ->
             Simplifier (StepResult (TState instr config))
         step a q = do
-            next <- transit a
-            if (isStuck next || isFinal next || isStopped next || shouldStop next)
```
Comment (jberthold) [inline kore/src/Kore/Exec/GraphTraversal.hs:267]: The problem was that `shouldStop` was used here, but not in `checkLeftUnproven` below where "unproven" (stopped) states are turned into a different result.
A cleaner solution is to turn `Branch` into `Stopped`. The open PR #3192 will refactor this to keep the next states in `Stopped`, too, so no information is lost.

**Review by ana-pantilie — APPROVED** [review]
