### PR TITLE
Remove duplicates when generating a kore term from a substitution

### LINKED ISSUE #3912: Haskell backend booster returning a doubled substitution
[var-sub.tar.gz](https://github.com/user-attachments/files/15515837/var-sub.tar.gz)

Here, I have an RPC interaction which causes a crash in the Pyk which recieves the module back (assertion error). The assertion error is this one: https://github.com/runtimeverification/k/blob/c82beec7ff95d98eff96d2bfcfe9e77268387c59/pyk/src/pyk/kore/rpc.py#L522. This check is making sure that substitutions passed back only contains one entry per variable in the term. Maybe this just means the haskell backend needs to deduplicate substitution entries which are having the same value? Maybe it's indicative of a deeper bug?

The error I get in pyk is:

```
INFO 2024-05-31 15:34:03,889 pyk.kore.rpc - Received response from localhost:44205: 3 - execute
ERROR 2024-05-31 15:34:03,913 kevm_pyk.utils - Proof crashed: VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough
Duplicate substitution entry key: VarABI'Unds'y : SortInt{}
Traceback (most recent call last):
  File "/home/dev/src/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 237, in run_prover
    strategy.prove(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/home/dev/src/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 173, in prove
    prover.advance_proof(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/home/dev/src/k/pyk/src/pyk/proof/proof.py", line 500, in advance_proof
    results = self.step_proof(step)
  File "/home/dev/src/k/pyk/src/pyk/proof/reachability.py", line 780, in step_proof
    extend_result = self.kcfg_explore.extend_cterm(
  File "/home/dev/src/k/pyk/src/pyk/kcfg/explore.py", line 230, in extend_cterm
    cterm, next_states, depth, vacuous, next_node_logs = self.cterm_symbolic.execute(
  File "/home/dev/src/k/pyk/src/pyk/cterm/symbolic.py", line 133, in execute
    response = self._kore_client.execute(
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 1020, in execute
    return ExecuteResult.from_dict(result)
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 672, in from_dict
    return globals()[ExecuteResult._TYPES[StopReason(dct['reason'])]].from_dict(dct)  # type: ignore
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 767, in from_dict
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 767, in <genexpr>
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 496, in from_dict
    State._subst_to_dict(kore_term(dct['rule-substitution'])) if 'rule-substitution' in dct else None
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 522, in _subst_to_dict
    raise ValueError(f'Duplicate substitution entry key: {key.text}')
ValueError: Duplicate substitution entry key: VarABI'Unds'y : SortInt{}
```

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Fixes #3912

### CODE REVIEW

File: kore/src/Kore/Syntax/Json.hs [hunk 1]
```diff
@@ -124,6 +125,8 @@ fromSubstitution sort subst
             . fromTermLike
             . foldl1 TermLike.mkAnd
             . map toEquals
+            . Set.toList
+            . Set.fromList
```
Comment (jberthold) [inline kore/src/Kore/Syntax/Json.hs:129]: Of course this only addresses cases where the _same_ `Assignment` is duplicated in the substitution.
In `booster` there is code (in the pattern internalisation) which vets sets of assignments to decide what is a true substitution and what isn't.
If we continue to have problem reports we should find out whether and where `kore` generates invalid substitutions

**Review by jberthold — APPROVED** [review]
LGTM (to fix the immediate issue).

**Review by geo2a — APPROVED** [review]
