### PR TITLE
Split MultiApp into LeftAssoc and RightAssoc

### LINKED ISSUE #3502: `Invalid params` RPC response from `implies` endpoint
I am making a call via Pyk to the `implies` endpoint, but it seems to hit some kind of internal error (`-32602`, "Invalid Params") when doing so; my suspicion is perhaps that the terms I'm checking are too large for the underlying library? The implication in question is just sanity-checking whether a large concrete term unifies with itself (i.e. `client.implies(term, term)` in Pyk).

I'm running `kore-rpc` as:
```console
$ kore-rpc /home/bruce/code/c-semantics/.build/dist/lib/kcc/haskell/c-kompiled/definition.kore --server-port 5766 --module C
```
Version info:
```console
$ kore-rpc --version
Kore version 0.60.0.0
Git:
  revision:	b74e9f8d5b88f4550145abf90d7fb3e69e072963
  branch:	HEAD
  last commit:	Thu Feb 9 16:26:54 2023 -0700
```

Reproduction files:
* [C semantics definition](https://drive.google.com/file/d/12tzsmK2pvUNNXKJFBij17YBLdStn1byF/view?usp=share_link)
* [Pyk bug report](https://drive.google.com/file/d/1p0cS_jhBA0dxsppNKGRWB5dMWmiBCo7e/view?usp=share_link) - contains the actual JSON blobs that get sent to the RPC server, as well as the response I'm seeing

Let me know if there is any more context I can provide.

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Fixes  #3502

Implements `Left/RightAssoc` as suggested in the issue:

```json
{ 
    "tag": "LeftAssoc",
    "symbol": ...,
    "sorts" : ...,
    "argss": ...
}
```

### CODE REVIEW

File: kore-rpc-types/src/Kore/Syntax/Json/Types.hs [hunk 1]
```diff
@@ -265,8 +270,10 @@ lexicalCheck p =
             reportErrors txt "string literal" checkLatin1Range
         -- Input supports std Unicode (as per json spec). toJSON could
         -- check that only allowed escape sequences will be generated.
-        KJMultiApp{symbol = Id n} ->
-            reportErrors n "multi-app symbol" checkSymbolName
+        KJLeftAssoc{symbol = Id n} ->
+            reportErrors n "left-assoc symbol" checkSymbolName
+        KJRightAssoc{symbol = Id n} ->
+            reportErrors n "left-assoc symbol" checkSymbolName
```
Comment (jberthold) [inline kore-rpc-types/src/Kore/Syntax/Json/Types.hs:276]: s/left/right/  :smirk:
