### PR TITLE
Use exec hash to identify versioning issues

### LINKED ISSUE #3077: Compact error/segmentation fault
```
$ /Users/anapantilie/RV/haskell-backend/.build/kore/bin/kore-exec ./demo-kompiled/haskellDefinition.bin --module DEMO --pattern .krun-2022-05-30-21-24-31-rUHXdqwjRD/tmp.in.QZx08RsJH8
[1]    9547 segmentation fault  /Users/anapantilie/RV/haskell-backend/.build/kore/bin/kore-exec  --module DEM
```

```
$ /Users/anapantilie/RV/haskell-backend/.build/kore/bin/kore-exec ./demo-kompiled/haskellDefinition.bin --module DEMO --pattern .krun-2022-05-30-21-24-31-rUHXdqwjRD/tmp.in.QZx08RsJH8
Invalid non-NFData closure (type 818185033) in Compact
kore-exec: [6753] Error (ErrorParse):
    Failed to import compact
```
[kore-exec.tar.gz](https://github.com/runtimeverification/haskell-backend/files/8800179/kore-exec.tar.gz)

- [x] #3085
- [x] #3086

### LINKED ISSUE #3086: Make the errors with reading the serialized data more user-friendly

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #3086

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

File: kore/app/exec/Main.hs [hunk 1]
```diff
@@ -719,20 +714,30 @@ koreRun exeLastModifiedTime LocalOptions{execOptions, simplifierx} = do
...
+            compact <- compactWithSharing serializedDefinition
+            withFile outputFile WriteMode $ \outputHandle -> do
+                hPut outputHandle (Binary.encode execHash)
+                hPutCompact outputHandle compact
             return (locations, ExitSuccess)
+  where
+    KoreExecOptions{definitionFileName} = execOptions
+    KoreExecOptions{mainModuleName} = execOptions
+    KoreExecOptions{outputFileName} = execOptions
+    KoreExecOptions{koreSolverOptions} = execOptions
```
Comment (jberthold) [inline kore/app/exec/Main.hs:740]: (nit)
```suggestion
    KoreExecOptions { definitionFileName
                    , mainModuleName
                    , outputFileName
                    , koreSolverOptions
                    } = execOptions
```
(or using `RecordWildCards` and `KoreExecOptions{..}`, but which might not be popular)

File: kore/app/share/GlobalMain.hs [hunk 2]
```diff
@@ -590,42 +585,51 @@ deserializeDefinition ::
...
+                ByteString.hGet definitionHandle 32
+                    <&> Binary.decode
+            magicNumber <-
+                ByteString.hGet definitionHandle 16
+                    <&> ByteString.drop 8
+                    <&> Binary.decode @Word64
+            case magicNumber of
+                0x7c155e7a53f094f2 -> do
+                    checkFingerprint fingerprint
+                    hSeek definitionHandle AbsoluteSeek 32
```
Comment (jberthold) [inline kore/app/share/GlobalMain.hs:618]: I think you would not need to check the magic number by yourself here, `hUnsafeGetCompact` will do that (by way of `Binary.decodeOrFail` calling [`Binary.get`](https://hackage.haskell.org/package/compact-0.2.0.0/docs/src/Data.Compact.Serialize.html#local-8214565720323790560). 
That would save rewinding the handle.

File: kore/app/share/GlobalMain.hs [hunk 3]
```diff
@@ -590,42 +585,51 @@ deserializeDefinition ::
...
                         definitionFilePath
                         mainModuleName
+      where
+        readContents definitionHandle = do
+            fingerprint <-
+                ByteString.hGet definitionHandle 32
+                    <&> Binary.decode
+            magicNumber <-
+                ByteString.hGet definitionHandle 16
+                    <&> ByteString.drop 8
```
Comment (jberthold) [inline kore/app/share/GlobalMain.hs:613]: Not sure about the `32` and `16`... (and why are 8 bytes dropped?) but I guess you have inspected the saved file in hex...

File: kore/app/share/GlobalMain.hs (hunk 2 above)
Comment (ana-pantilie) [reply kore/app/share/GlobalMain.hs:618]: I think the reason this check was added was because depending on whether that magic number exists we know if the file is binary or textual, so we can delegate to the appropriate procedure.

File: kore/app/share/GlobalMain.hs [hunk 4]
```diff
@@ -590,42 +584,51 @@ deserializeDefinition ::
...
+                        hUnsafeGetCompact definitionHandle
+                            >>= either errorParse (return . getCompact)
+                    return (Just serializedDefinition)
+                _ -> return Nothing
+
+        checkFingerprint fingerprint = do
+            execHash <- getExecutablePath >>= Fingerprint.getFileHash
+            unless
+                (execHash == fingerprint)
+                ( error
```
Comment (jberthold) [inline kore/app/share/GlobalMain.hs:628]: Maybe `errorParse` here?

Comment (ana-pantilie) [inline kore/app/share/GlobalMain.hs:628]:
```suggestion
                ( errorParse
```
