### PR TITLE
kore-rpc Catch any runtime exception and send as error

### LINKED ISSUE #3520: `kore-rpc` does not send response on solver crash
## Reproduction

Kompile definition:

[definition.txt](https://github.com/runtimeverification/haskell-backend/files/10831782/definition.txt)

The definition can be produced by cloning https://github.com/runtimeverification/evm-semantics/commit/c9b14f64be620c2ce7cb12b466ba972ac822f990, then building the Foundry test definition:

```
$ make tests/foundry/out/kompiled/timestamp
```

Start `kore-rpc`:

```
$ kore-rpc tests/foundry/out/kompiled/definition.kore --module FOUNDRY-MAIN --server-port 3000 --smt-timeout 1 --smt-retry-limit 1
```

Send request:

[request.txt](https://github.com/runtimeverification/haskell-backend/files/10831187/request.txt)

```
$ netcat localhost 3000 < request.txt
```

Server log:

```
kore-rpc: user error (Unexpected result from the SMT solver:
  Command: (push 1 )
  Expected: success
  Result: (error "line 2038 column 8: canceled" )
)
```

## Actual behavior

`kore-rpc` does not send response, which makes the client hang indefinitely.

## Expected behavior

`kore-rpc` should send error response with an application defined error code.

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Fixes #3520 

image

### CODE REVIEW

File: kore/src/Kore/JsonRpc.hs [hunk 1]
```diff
@@ -543,10 +544,11 @@ srv serverState moduleName Log.LoggerEnv{logAction} runSMT = do
 
     cancelError = ErrorObj "Request cancelled" (-32000) Null
 
-    bracketOnReqException before onCancel thing =
+    bracketOnReqException before onError thing =
         mask $ \restore -> do
             a <- before
-            restore (thing a) `catch` \(_ :: ReqException) -> onCancel a
+            (restore (thing a) `catch` \(_ :: ReqException) -> onError cancelError a)
+                `catch` \(err :: SomeException) -> print err >> onError (serverError "crashed" $ toJSON $ show err) a
```
Comment (jberthold) [inline kore/src/Kore/JsonRpc.hs:551]: If we catch all exceptions here we won't need the `withErrHandler` inside `respond` any more.

**Review by jberthold — APPROVED** [review]
We can merge this and follow-up with more changes to un-block people.
