### PR TITLE
Fail when checking definition with Z3 returns Unknown

### LINKED ISSUE #3619: Possible to run with a potentially inconsistent SMT setup
The [initialisation code for the SMT solver](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Rewrite/SMT/Lemma.hs#L84-L88) checks the prelude of all declarations and `smt-lemma` assertions and will refuse to work when it  is `Unsat`, but it does not prevent running with a setup that yields `Unknown`.

The `Unknown` result may come from a timeout, where it might be OK to proceed, but it can also come from the solver being (algorithmically) unable to decide even the lemmas of the prelude. This will prevent the solver from ever returning a `Sat` result for any subsequent queries, it will always be `Unknown` or `Unsat`.

At least there should be a warning emitted during the setup which points this out to the user.

Case in point: this [bug_report.tar.gz (compressed and some artefacts removed](https://github.com/runtimeverification/haskell-backend/files/11974788/bug_report.tar.gz) was provided with a report of the SMT solver failing with `ErrorDecidePredicateUnknown` for a simplification RPC request. Its SMT prelude contains inconsistent lemmas which the solver cannot decide.

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Fixes #3619
The definition provided in the above issue now throws the following error:

```
kore-rpc: [4462799] Error (ErrorException):
    The definitions sent to the solver may not be consistent (Z3 timed out).
    CallStack (from HasCallStack):
      error, called at src/Kore/Rewrite/SMT/Lemma.hs:180:9 in kore-0.60.0.0-inplace:Kore.Rewrite.SMT.Lemma
```

### CODE REVIEW

**Review by geo2a — APPROVED** [review]

File: kore/src/Kore/Rewrite/SMT/Lemma.hs [hunk 1]
```diff
@@ -84,8 +84,11 @@ declareSMTLemmas ::
 declareSMTLemmas tools lemmas = do
     declareSortsSymbols $ smtData tools
     mapM_ declareRule lemmas
-    isUnsatisfiable <- fmap (Unsat ==) <$> SMT.check
-    when (fromMaybe False isUnsatisfiable) errorInconsistentDefinitions
+    SMT.check >>= \case
```
Comment (jberthold) [inline kore/src/Kore/Rewrite/SMT/Lemma.hs:87]: CI failures... do we need to retry or bump up the timeout here?
